routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Spatie\Activitylog\Models\Activity;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('admin')->prefix('admin')->name('admin.')->group(function (){
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
//	ADMIN_PAGE
	Route::resource('/page','PageController');
	Route::post('/page/updateStatus', 'PageController@updateStatus')->name('page.updateStatus');
	Route::post('/page/deletePage', 'PageController@deletePage')->name('page.deletePage');
	Route::get('/page/getAjaxForm', 'PageController@getAjaxForm')->name('page.getAjaxForm');
	Route::post('/page/action', 'PageController@action')->name('page.action');
// ADMIN_POST CAT
	Route::resource('/post_cat','PostCatController');
	Route::get('/postCat/getListPostCat', 'PostCatController@getListPostCat')->name('postCat.getListPostCat');
	Route::get('/postCat/getListParent', 'PostCatController@getListParent')->name('postCat.getListParent');
	Route::post('/postCat/deletePostCat', 'PostCatController@deletePostCat')->name('postCat.deletePostCat');
	Route::post('/postCat/action', 'PostCatController@action')->name('postCat.action');
//	ADMIN POST
	Route::resource('/post','PostController');
	Route::post('/post/updateStatus', 'PostController@updateStatus')->name('post.updateStatus');
	Route::post('/post/deletePost', 'PostController@deletePost')->name('post.deletePost');
	Route::post('/post/action', 'PostController@action')->name('post.action');

});
Route::get('/test',function (){
//	$activity = Activity::all()->last();
//	dd($activity->changes());
//	$data = auth('admin')->user()->activity;
//	dd($data);
});
//Route::namespace('ajax')->prefix('ajax')->name('ajax.')->group(function (){
//	Route::post('/page', 'PageController@index')->name('page');
//});

resources/views/admin/page/page.blade.php
@extends('admin.layouts.index')
@section('title','Quản lý trang')
@section('content')
    <div class="boxed">

        <!--CONTENT CONTAINER-->
        <!--===================================================-->
        <div id="content-container">
            <div id="page-head">

                <!--Page Title-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <div id="page-title">
                    <h1 class="page-header text-overflow">@lang('admin.page')</h1>
                    <div class="text-right" style="margin-right: 30px;">
                        <button class="btn btn-primary" id="add_page">@lang('admin.add_page')</button>
                        <input type="hidden" id="add_page_hidden" value="{{route('admin.page.create')}}">
                    </div>
                </div>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End page title-->


                <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
                    <li><a href="{{ route('admin.home') }}"><i class="demo-pli-home"></i></a></li>
                    <li>Trang</li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->

            </div>


            <!--Page content-->
            <!--===================================================-->
            <div id="page-content">

            {{--<div class="panel">--}}
            {{--<div class="panel-heading">--}}
            {{--<h3 class="panel-title">Full width content</h3>--}}
            {{--</div>--}}
            {{--<!--Summernote-->--}}
            {{--<!--===================================================-->--}}
            {{--<div id="demo-summernote">--}}
            {{--<h4><span style="color: rgb(206, 198, 206); font-family: inherit; line-height: 1.1;">Please, write text here!</span><br></h4><h4><font color="#9c9c94"></font></h4>--}}
            {{--</div>--}}
            {{--<!--===================================================-->--}}
            {{--<!-- End Summernote -->--}}
            {{--</div>--}}


            <!-- Basic Data Tables -->
                <!--===================================================-->
                <div class="panel data-table">
                    <div class="panel-heading">
                        <h3 class="panel-title data-table-title">Danh sách trang</h3>
                    </div>
                    <div class="panel-body">
                        <select class="selectpicker" name="actions" id="actions">
                            <option value="1">Đăng</option>
                            <option value="-1">Chờ xét duyệt</option>
                            <option value="4">Xóa</option>
                        </select>
                        <button class="btn btn-primary" style="margin-bottom: 15px;" id="action">Thao Tác</button>
                        {!! $dataTable->table() !!}
                    </div>
                </div>
                <!--===================================================-->
                <!-- End Striped Table -->
            </div>
            <!--===================================================-->
            <!--End page content-->

        </div>
        <!--===================================================-->
        <!--END CONTENT CONTAINER-->
        <div class="modal" id="myModal">
            <div class="modal-dialog modal-lg" style="width: 80%;">
                <div class="modal-content">
                    <div class="loader loading-area">
                        <img class="loading-image" src="{{ asset('admin/img/loading/loading.gif') }}">
                        <p class="loading-text">@lang('admin.loading') ...</p>
                    </div>
                    <div class="modal-header" style="border-bottom: 1px solid #eee;">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title">@lang('admin.add_page')</h4>
                    </div>
                    <div class="container"></div>
                    <div class="modal-body" id="modal-body-id">

                    </div>
                    {{--<div class="modal-footer">--}}
                    {{--<a href="#" data-dismiss="modal" class="btn btn-info">@lang('admin.close')</a>--}}
                    {{--<button class="btn btn-primary" id="save">@lang('admin.save')</button>--}}
                    {{--</div>--}}
                </div>
            </div>
        </div>
        {{--Popup Delete--}}
        <div class="modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                        <h4 class="modal-title">Modal title</h4>
                    </div>

                    <div class="modal-body">
                        <p>One fine body ...........</p>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                        <button class="btn btn-primary" type="button">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        {{--@include('admin.layouts.aside')--}}
        {{--@include('admin.layouts.navigation')--}}
    </div>
@endsection

@section('js')
    {!! $dataTable->scripts() !!}
    <script>
        function updateStatus(id){
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method: 'POST',
                url: "{{route('admin.page.updateStatus')}}",
                dataType: 'text',
                data: {
                    id : id
                },
                beforeSend: function() {
                },
                complete: function() {
                },
                success: function(data) {
                    window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                    setTimeout(function(){
                        iziToast.success({
                            position: 'topRight',
                            title: '@lang('admin.info')',
                            message: data
                        });
                    }, 1000);
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        }
        // ADD PAGE MODAL
        $('#add_page').click(function () {
            var action = $('#add_page_hidden').val();
            $('#myModal').modal('show');
            $('#modal-body-id').html('');
            $('#myModal .modal-title').text('@lang('admin.add_page')');

            $.ajax({
                url: action,
                dataType: 'html',
                method: 'GET',
                data: {
                },
                beforeSend: function () {
                },
                complete: function () {
                },
                success: function (data) {
                    $('#modal-body-id').prepend(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });
        // VIEW PAGE MODAL
        function viewPage(obj){
            var action = obj.getAttribute('data-url');
            $('#myModal').modal('show');
            $('#modal-body-id').html('');
            $('#myModal .modal-title').text('@lang('admin.view_page')');
            $.ajax({
                url: action,
                dataType: 'html',
                method: 'GET',
                data: {

                },
                beforeSend: function () {
                },
                complete: function () {
                },
                success: function (data) {
                    $('#modal-body-id').prepend(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        }
        // UPDATE PAGE MODAL
        function updatePage(obj){
            var action = obj.getAttribute('data-url');
            $('#myModal').modal('show');
            $('#modal-body-id').html('');
            $('#myModal .modal-title').text('@lang('admin.edit_page')');
            $.ajax({
                url: action,
                dataType: 'html',
                method: 'GET',
                data: {

                },
                beforeSend: function () {
                },
                complete: function () {
                },
                success: function (data) {
                    $('#modal-body-id').prepend(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        }
        // Delete Page
        function deletePage(id){
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method: 'POST',
                url: "{{route('admin.page.deletePage')}}",
                dataType: 'json',
                data: {
                    id : id
                },
                beforeSend: function() {
                },
                complete: function() {
                },
                success: function(response) {
                    if(response.result == 'success'){
                        window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                        setTimeout(function(){
                            iziToast.success({
                                position: 'topRight',
                                title: '@lang('admin.info')',
                                message: response.info
                            });
                        }, 1000);
                    }else{
                        window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                        setTimeout(function(){
                            iziToast.error({
                                position: 'topRight',
                                title: '@lang('admin.info')',
                                message: response.info
                            });
                        }, 1000);
                    }
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        }
        // LIST CHECKBOX ACTION
        $('#checkAll').click(function () {
            var checkBoxes = $(".checkItem");
            checkBoxes.prop("checked", !checkBoxes.prop("checked"));
        });
        // ACTION STATUS AND DELETE
        $('#action').click(function () {
            var action = $('#actions').val();
            var item_checked = [];
            $.each($("input[name='checkItem']:checked"), function(){
                item_checked.push($(this).val());
            });
            console.log(item_checked);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method: 'POST',
                url: "{{route('admin.page.action')}}",
                dataType: 'json',
                data: {
                    action       : action,
                    item_checked : item_checked
                },
                beforeSend: function() {
                },
                complete: function() {
                },
                success: function(response) {
                    if(response.result == 'success'){
                        window.LaravelDataTables["dataTableBuilder"].ajax.reload();
                        setTimeout(function(){
                            iziToast.success({
                                position: 'topRight',
                                title: '@lang('admin.info')',
                                message: response.info
                            });
                        }, 1000);
                    }else{
                        // setTimeout(function(){
                        iziToast.error({
                            position: 'topRight',
                            title: '@lang('admin.info')',
                            message: response.info
                        });
                        // }, 1000);
                    }
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });
    </script>
@stop

resources/views/admin/page/page_detail.blade.php
        <div id="page-content">
            <div class="panel blog blog-details">
                <div class="panel-body">
                    <div class="blog-title media-block">
                        <div class="media-right textright">
                            <a href="#" class="btn btn-icon demo-psi-twitter icon-lg add-tooltip" data-original-title="Twitter" data-container="body"></a>
                            <a href="#" class="btn btn-icon demo-psi-instagram icon-lg add-tooltip" data-original-title="Instagram" data-container="body"></a>
                        </div>
                        <div class="media-body">
                            <a href="#" class="btn-link">
                                <h1>{{ $page->title }}</h1>
                            </a>
                            <p>@lang('admin.by')
                                <a href="#" class="btn">{{ $page->user->name }}
                                    <span class="label label-success">{{ $page->CreatedDate }}</span>
                                </a>
                            </p>
                            <p>
                                @lang('admin.number_view'): <span class="mar-rgt"> {{ $page->viewer }} @lang('admin.view')</span>
                                <br>
                            </p>
                            {{--<p>--}}
                                {{--@lang('admin.status'): <span class="mar-rgt"> {{ $page->Statu }} @lang('admin.view')</span>--}}
                            {{--</p>--}}
                        </div>
                    </div>
                    <hr>
                    <div class="blog-content">
                        <div class="blog-body">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>

resources/views/admin/page/page_popup.blade.php
<form class="panel-body form-horizontal form-padding"  id="form-action" action="{{ $action }}" method="post">
    <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
        @if($id)
            {{ method_field('PATCH') }}
        @endif
    <!--Text Input-->
    <div class="form-group">
        <label class="col-md-1 control-label" for="demo-text-input">Tiêu đề</label>
        <div class="col-md-11">
            <input type="text" name="title" value="@if($id){{$page->title}}@endif" id="demo-text-input" class="form-control" placeholder="Text">
            <small class="help-block">This is a help text</small>
        </div>
    </div>

    <!--Textarea-->
    <div class="form-group">
        <label class="col-md-1 control-label" for="demo-textarea-input">Nội dung</label>
        <div class="col-md-11">
            <textarea id="demo-summernote" name="content" rows="9" class="form-control" placeholder="Your content here..">
                @if($id){{$page->content}}@endif
            </textarea>
        </div>
    </div>

    <div class="form-group pad-ver">
        <label class="col-md-1 control-label">Trang thái</label>
        <div class="col-md-11">
            <!-- Radio Buttons -->
            <div class="radio">
                <input id="demo-form-radio" class="magic-radio" type="radio" value="1"  @if($id)  @if($page->status == '1') checked @endif @endif name="status" checked="">
                <label for="demo-form-radio">Đăng</label>
            </div>
            <div class="radio">
                <input id="demo-form-radio-2" class="magic-radio" type="radio" value="-1" @if($id)  @if($page->status == '-1') checked @endif @endif name="status">
                <label for="demo-form-radio-2">Chờ</label>
            </div>
        </div>
    </div>
    <div class="form-group" style="padding-top: 40px; text-align: right; border-top: 1px solid #e8e8e8;">
            <a href="#" data-dismiss="modal" class="btn btn-info">@lang('admin.close')</a>
            <button class="btn btn-primary" id="save">@lang('admin.save')</button>
    </div>
</form>
<script>
    $('#demo-summernote').summernote({
        height : '230px'
    });
</script>
<style>
    .modal-dialog { z-index: 1040; }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $( "#save").on("click",function (e) {
            e.preventDefault();
            var $flag = true;
            if ($flag == true) {
                var action = $("#form-action").attr("action");
                var request_method = $("#form-action").attr("method");
                var form_data = new FormData(document.getElementById('form-action'));
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url: action,
                    type: request_method,
                    data: form_data,
                    processData: false,
                    contentType: false,
                    cache: false,
                    error: function(xhr, ajaxOptions, thrownError) {
                        alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                    }
                }).done(function (data) {
                    if(data.success){
                        if(data.result == 'add'){
                            iziToast.success({
                                position: 'topCenter',
                                title: '@lang('admin.info')',
                                message: data.success
                            });
                            var table = $("#dataTableBuilder").DataTable();
                            table.ajax.reload();
                        }else{
                            $('#myModal').modal('hide');
                            iziToast.success({
                                position: 'topCenter',
                                title: '@lang('admin.info')',
                                message: data.success
                            });
                            var table = $("#dataTableBuilder").DataTable();
                            table.ajax.reload();
                        }

                    }else{
                        jQuery.each(data.errors, function(key, value){
                            iziToast.error({
                                position: 'topRight',
                                title: '@lang('admin.info')',
                                message: value
                            });
                        });
                    }
                });
            }
        });
    });
</script>