routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Spatie\Activitylog\Models\Activity;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('admin')->prefix('admin')->name('admin.')->group(function (){
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
//	ADMIN_PAGE
	Route::resource('/page','PageController');
	Route::post('/page/updateStatus', 'PageController@updateStatus')->name('page.updateStatus');
	Route::post('/page/deletePage', 'PageController@deletePage')->name('page.deletePage');
	Route::get('/page/getAjaxForm', 'PageController@getAjaxForm')->name('page.getAjaxForm');
	Route::post('/page/action', 'PageController@action')->name('page.action');
// ADMIN_POST CAT
	Route::resource('/post_cat','PostCatController');
	Route::get('/postCat/getListPostCat', 'PostCatController@getListPostCat')->name('postCat.getListPostCat');
	Route::get('/postCat/getListParent', 'PostCatController@getListParent')->name('postCat.getListParent');
	Route::post('/postCat/deletePostCat', 'PostCatController@deletePostCat')->name('postCat.deletePostCat');
	Route::post('/postCat/action', 'PostCatController@action')->name('postCat.action');
//	ADMIN POST
	Route::resource('/post','PostController');
	Route::post('/post/updateStatus', 'PostController@updateStatus')->name('post.updateStatus');
	Route::post('/post/deletePost', 'PostController@deletePost')->name('post.deletePost');
	Route::post('/post/action', 'PostController@action')->name('post.action');

});
Route::get('/test',function (){
//	$activity = Activity::all()->last();
//	dd($activity->changes());
//	$data = auth('admin')->user()->activity;
//	dd($data);
});
//Route::namespace('ajax')->prefix('ajax')->name('ajax.')->group(function (){
//	Route::post('/page', 'PageController@index')->name('page');
//});

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\PostDatatable;
use App\Model\Post;
use App\Model\Post_cat;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Yajra\DataTables\DataTables;
use Yajra\DataTables\Html\Builder;

class PostController extends Controller
{

	protected $builder;

	/**
	 * PageController constructor.
	 * @param Builder $builder
	 */
	public function __construct(Builder $builder)
	{
		$this->builder = $builder;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @param PostDatatable $datatable
	 * @return \Illuminate\Http\Response
	 */
	public function index(PostDatatable $datatable)
	{
		return $datatable->render('admin.post.post');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return $this->getAjaxForm($id = null);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function getAjaxForm($id= null){
		$categories = Post_cat::where('parent_id','>',0)->get();
		if ($id) {
			$action = route('admin.post.update',$id);
			$post = Post::where('id',$id)->first();
			return response()->view('admin.post.post_popup',compact('action','id','post','categories'));
		}
		$action = route('admin.post.store');
		return response()->view('admin.post.post_popup',compact('action','id','categories'));
	}

	public function store(Request $request)
	{
		$validator = \Validator::make($request->all(), [
			'title' 		=> 'required|unique:posts,title',
			'description' 	=> 'required',
			'content' 		=> 'required',
			'post_cat_id' 	=> 'required',
			'status' 		=> 'required',
		]);
		if ($validator->fails())
		{
			return response()->json(['errors'=>$validator->errors()->all()]);
		}
		$data = $request->all();
		if ($request->hasFile('fileUpload')) {
			$file = $request->fileUpload;
			$fileName=$file->getClientOriginalName();
			$file->move(public_path('uploads/post'),$fileName);
			$data['image']='uploads/post/'.$fileName;
			$data['slug']=str_slug($data['title']);
			$data['title_seal']=str_slug($data['title'],' ');
			$data['user_id']= auth('admin')->user()->id;
			$data['category_id']=Post_cat::where('id', $request->post_cat_id)->first()->parent_id;
		}
		Post::create($data);
		return response()->json([
			'result' =>'add',
			'success'=>trans('admin.add_post_success')
		]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$post = Post::with('user')->where('id',$id)->first();
		return response()->view('admin.post.post_detail',compact('post'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		return $this->getAjaxForm($id);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param Post $post
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, Post $post)
	{
		$validator = \Validator::make($request->all(), [
			'title' => [
				'required',
				Rule::unique('posts')->ignore($post->id),
			],
			'description' 	=> 'required',
			'content' 		=> 'required',
			'post_cat_id' 	=> 'required',
			'status' 		=> 'required',
		]);
		if ($validator->fails())
		{
			return response()->json(['errors'=>$validator->errors()->all()]);
		}

		$data=$request->all();
		if ($request->hasFile('fileUpload')) {
			$file = $request->fileUpload;
			$fileName=$file->getClientOriginalName();
			$file->move(public_path('uploads/post'),$fileName);
			$data['slug']=str_slug($data['title']);
			$data['title_seal']=str_slug($data['title'],' ');
			$data['image']='uploads/post/'.$fileName;
			$data['user_id']= auth('admin')->user()->id;
			$data['category_id']=Post_cat::where('id', $request->post_cat_id)->first()->parent_id;
		}else{
			$data['user_id']= auth('admin')->user()->id;
			$data['category_id']=Post_cat::where('id', $request->post_cat_id)->first()->parent_id;
		}
		$post->update($data);
		activity()
			->performedOn($post)
			->causedBy(auth('admin')->user())
			->log('Bài viết <a href="'.route('admin.post.show',$post->id).'">'.$post->title.'</a> đã chỉnh sửa');
		return response()->json([
			'result' =>'update',
			'success'=>trans('admin.update_post_success')
		]);
	}

	public function updateStatus(Request $request)
	{
		$post = Post::findOrFail($request->id);
		if($post->isactived())
		{
			$post->pending();
			return trans('admin.pending_success');
		}
		$post->active();
		return trans('admin.active_success');
	}

	public function deletePost(Request $request)
	{
		$post = Post::findOrFail($request->id);
		if($post->isactived())
		{
			$info =  trans('admin.delete_post_fail');
			return $data = response()->json(array(
				'result' => 'fail',
				'info'   => $info
			));
		}
		$post->delete();
		$info =  trans('admin.delete_post_success');
		return $data = response()->json(array(
			'result' => 'success',
			'info'   => $info
		));
	}

	public function action(Request $request){
		$action = $request->action;
		$item_checked = $request->item_checked;
		if(empty($item_checked)){
			return response()->json([
				'result' => 'fail',
				'info'   => trans('admin.error_select_item')
			]);
		}
//		Delete Status
		if($action == 4){
			$count = 0;
			foreach ($item_checked as $item){
				$post = Post::findOrFail($item);
				if($post->status != '1'){
					$post->delete();
					$count ++;
				}
			}
			return response()->json([
				'result' => 'success',
				'info'   => 'Đã xóa '.$count.' mục trong danh sách'
			]);
		}
//		Update Status
		$count = 0;
		foreach ($item_checked as $item){
			$post = Post::findOrFail($item);
			if($post->status != "$action"){
				$post->update(['status' => "$action"]);;
				$count ++;
			}
		}
		return response()->json([
			'result' => 'success',
			'info'   =>'Đã cập nhật trạng thái '.$count.' mục trong danh sách'
		]);
	}
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		//
	}
}

resources/views/admin/post/list_parent.blade.php
<option value="0">Chọn cấp</option>
@foreach($parents as $item)
    <option value="{{ $item->id }}" @if( isset($post_cat)) @if($post_cat->parent_id == $item->id) selected @endif @endif>{{ $item->title }}</option>
@endforeach

resources/views/admin/post/list_post_cat.blade.php
@foreach($data as $item)
    <tr>
        <td>
            <input name="checkItem" value="{{ $item->id }}" style="cursor: pointer;" class="checkItem magic-checkbox" type="checkbox" id="{{ $item->id }}" />
            <label for="{{ $item->id }}"></label>
        </td>
        <td>{{ $item->id }}</td>
        <td>{{ str_repeat('---- ', $item->level).$item->title }}</td>
        <td>{{ $item->level }}</td>
        <td>{{ $item->user->name }}</td>
        <td>{{ $item->CreatedDate }}</td>
        <td>{{ $item->UpdateDate }}</td>
        <td>
            <a onclick = "updatePage(this);" data-url="{{ route('admin.post_cat.edit', $item->id) }}" href="javascript:void(0);" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> @lang('admin.edit')</a>
            <a href="#delete-{{$item->id}}" onclick="deletePostCat('{{ $item->id }}');" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> @lang('admin.delete')</a>
        </td>
    </tr>
@endforeach()

resources/views/admin/post/post_cat.blade.php
@extends('admin.layouts.index')
@section('title','Quản lý danh mục bài viết')
@section('content')
    <div class="boxed">

        <!--CONTENT CONTAINER-->
        <!--===================================================-->
        <div id="content-container">
            <div id="page-head">

                <!--Page Title-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <div id="page-title">
                    <h1 class="page-header text-overflow">@lang('admin.post_cat')</h1>
                    <div class="text-right" style="margin-right: 30px;">
                        <button class="btn btn-primary" id="add_post_cat">@lang('admin.add_post_cat')</button>
                        <input type="hidden" id="add_post_cat_hidden" value="{{route('admin.post_cat.create')}}">
                    </div>
                </div>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End page title-->


                <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
                    <li><a href="{{ route('admin.home') }}"><i class="demo-pli-home"></i></a></li>
                    <li>@lang('admin.post_cat')</li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->

            </div>


            <!--Page content-->
            <!--===================================================-->
            <div id="page-content">

            {{--<div class="panel">--}}
            {{--<div class="panel-heading">--}}
            {{--<h3 class="panel-title">Full width content</h3>--}}
            {{--</div>--}}
            {{--<!--Summernote-->--}}
            {{--<!--===================================================-->--}}
            {{--<div id="demo-summernote">--}}
            {{--<h4><span style="color: rgb(206, 198, 206); font-family: inherit; line-height: 1.1;">Please, write text here!</span><br></h4><h4><font color="#9c9c94"></font></h4>--}}
            {{--</div>--}}
            {{--<!--===================================================-->--}}
            {{--<!-- End Summernote -->--}}
            {{--</div>--}}


            <!-- Basic Data Tables -->
                <!--===================================================-->
                <div class="panel data-table">
                    <div class="panel-heading">
                        <h3 class="panel-title data-table-title" style="text-transform: uppercase;">Danh mục bài viết</h3>
                    </div>
                    <div class="panel-body">
                        <select class="selectpicker" name="actions" id="actions">
                            <option value="4">Xóa</option>
                        </select>
                        <button class="btn btn-primary" style="margin-bottom: 15px;" id="action">Thao Tác</button>
                        <table id="demo-dt-basic_info"
                               {{--class="display" width="100%" cellspacing="0"--}}
                               class="table dataTable no-footer" id="dataTableBuilder" role="grid" aria-describedby="dataTableBuilder_info" style="width: 1049px;"
                               {{--class="table table-striped table-bordered dataTable no-footer dtr-inline" cellspacing="0" width="100%" role="grid" aria-describedby="demo-dt-basic_info" style="width: 100%;"--}}
                        >
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" style="cursor: pointer;" class="magic-checkbox" name="checkAll" id="checkAll">
                                    <label for="checkAll"></label>
                                </th>
                                <th>ID</th>
                                <th>Tiêu đề</th>
                                <th>Cấp</th>
                                <th>Người tạo</th>
                                <th>Tạo lúc</th>
                                <th>Cập nhật</th>
                                <th>Tác vụ</th>
                            </tr>
                            </thead>
                            <tbody id="list-post-cat">

                            </tbody>
                        </table>
                    </div>
                </div>
                <!--===================================================-->
                <!-- End Striped Table -->
            </div>
            <!--===================================================-->
            <!--End page content-->

        </div>
        <!--===================================================-->
        <!--END CONTENT CONTAINER-->
        <div class="modal" id="myModal">
            <div class="modal-dialog modal-lg" style="width: 60%;">
                <div class="modal-content">
                    <div class="loader loading-area">
                        <img class="loading-image" src="{{ asset('admin/img/loading/loading.gif') }}">
                        <p class="loading-text">@lang('admin.loading') ...</p>
                    </div>
                    <div class="modal-header" style="border-bottom: 1px solid #eee;">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title">@lang('admin.add_page')</h4>
                    </div>
                    <div class="container"></div>
                    <div class="modal-body" id="modal-body-id">
                    </div>
                    {{--<div class="modal-footer">--}}
                    {{--<a href="#" data-dismiss="modal" class="btn btn-info">@lang('admin.close')</a>--}}
                    {{--<button class="btn btn-primary" id="save">@lang('admin.save')</button>--}}
                    {{--</div>--}}
                </div>
            </div>
        </div>
        {{--@include('admin.layouts.aside')--}}
        {{--@include('admin.layouts.navigation')--}}
    </div>
@stop

@section('js')
    <script>
        $(document).ready(function () {
            load_list_post_cat();
        });
        // LIST POST CAT
        function load_list_post_cat(){
            $('#list-post-cat').html('');
            $.ajax({
                url: '{{ route('admin.postCat.getListPostCat') }}',
                dataType: 'html',
                method: 'GET',
                data: {
                },
                beforeSend: function () {
                },
                complete: function () {
                },
                success: function (data) {
                    $('#list-post-cat').prepend(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        }
        // ADD POST CAT MODAL
        $('#add_post_cat').click(function () {
            var action = $('#add_post_cat_hidden').val();
            $('#myModal').modal('show');
            $('#modal-body-id').html('');
            $('#myModal .modal-title').text('@lang('admin.add_post_cat')');

            $.ajax({
                url: action,
                dataType: 'html',
                method: 'GET',
                data: {
                },
                beforeSend: function () {
                },
                complete: function () {
                },
                success: function (data) {
                    $('#modal-body-id').prepend(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });
        // UPDATE POST CAT MODAL
        function updatePage(obj){
            var action = obj.getAttribute('data-url');
            $('#myModal').modal('show');
            $('#modal-body-id').html('');
            $('#myModal .modal-title').text('@lang('admin.edit_post_cat')');
            $.ajax({
                url: action,
                dataType: 'html',
                method: 'GET',
                data: {

                },
                beforeSend: function () {
                },
                complete: function () {
                },
                success: function (data) {
                    $('#modal-body-id').prepend(data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        }
        // Delete Page
        function deletePostCat(id){
            $info = iziToast.question({
                overlay: true,
                toastOnce: true,
                id: 'question',
                title: '@lang('admin.hi')',
                message: '@lang('admin.action_question')',
                position: 'center',
                buttons: [
                    ['<button><b>@lang('admin.yes')</b></button>', function (instance, toast) {
                        $.ajax({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            method: 'POST',
                            url: "{{route('admin.postCat.deletePostCat')}}",
                            dataType: 'json',
                            data: {
                                id : id
                            },
                            beforeSend: function() {
                            },
                            complete: function() {
                            },
                            success: function(response) {
                                if(response.result == 'success'){
                                    load_list_post_cat();
                                    setTimeout(function(){
                                        iziToast.success({
                                            position: 'topCenter',
                                            title: '@lang('admin.info')',
                                            message: response.info
                                        });
                                    }, 1000);
                                }else{
                                    setTimeout(function(){
                                        iziToast.error({
                                            position: 'topCenter',
                                            title: '@lang('admin.info')',
                                            message: response.info
                                        });
                                    }, 1000);
                                }
                            },
                            error: function(xhr, ajaxOptions, thrownError) {
                                alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                            }
                        });
                        instance.hide({ transitionOut: 'fadeOut' }, toast);
                    }, true],
                    ['<button>@lang('admin.no')</button>', function (instance, toast) {

                        instance.hide({ transitionOut: 'fadeOut' }, toast);

                    }]
                ]
            });
        }
        // LIST CHECKBOX ACTION
        $('#checkAll').click(function () {
            var checkBoxes = $(".checkItem");
            checkBoxes.prop("checked", !checkBoxes.prop("checked"));
        });
        // ACTION STATUS AND DELETE
        $('#action').click(function () {
            var action = $('#actions').val();
            var item_checked = [];
            $.each($("input[name='checkItem']:checked"), function(){
                item_checked.push($(this).val());
            });
            console.log(item_checked);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method: 'POST',
                url: "{{route('admin.postCat.action')}}",
                dataType: 'json',
                data: {
                    action       : action,
                    item_checked : item_checked
                },
                beforeSend: function() {
                },
                complete: function() {
                },
                success: function(response) {
                    if(response.result == 'success'){
                        load_list_post_cat();
                        setTimeout(function(){
                            iziToast.success({
                                position: 'topCenter',
                                title: '@lang('admin.info')',
                                message: response.info
                            });
                        }, 1000);
                    }else{
                        iziToast.error({
                            position: 'topCenter',
                            title: '@lang('admin.info')',
                            message: response.info
                        });
                    }
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                }
            });
        });
    </script>
@stop

resources/views/admin/post/post_cat_popup.blade.php
<form class="panel-body form-horizontal form-padding"  id="form-action" action="{{ $action }}" method="post">
    <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
    <input type="hidden" id="id-post-cat" value="@if($id){{ $id }}@endif">
@if($id)
    {{ method_field('PATCH') }}
@endif
<!--Text Input-->
    <div class="form-group">
        <label class="col-md-1 control-label" for="demo-text-input">Tiêu đề</label>
        <div class="col-md-11">
            <input type="text" name="title" value="@if($id){{$post_cat->title}}@endif" id="demo-text-input" class="form-control" placeholder="Text">
            <small class="help-block">This is a help text</small>
        </div>
    </div>

    <div class="form-group pad-ver">
        <label class="col-md-1 control-label">Chọn cấp cha</label>
        <div class="col-md-11 col-sm-6">
            <select class="form-control" name="parent_id" id="parent-id">
            </select>
        </div>
    </div>
    <div class="form-group" style="padding-top: 40px; text-align: right; border-top: 1px solid #e8e8e8;">
        <a href="#" data-dismiss="modal" class="btn btn-info">@lang('admin.close')</a>
        <button class="btn btn-primary" id="save">@lang('admin.save')</button>
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function () {
        load_list_parent_cat();
    });
    // LIST Parent CAT
    function load_list_parent_cat(){
        $('#parent-id').html('');
        var id = $('#id-post-cat').val();
        $.ajax({
            url: "{{ route('admin.postCat.getListParent') }}",
            dataType: 'html',
            method: 'GET',
            data: {
                id : id
            },
            beforeSend: function () {
            },
            complete: function () {
            },
            success: function (data) {
                $('#parent-id').prepend(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
            }
        });
    }
    $(document).ready(function() {
        $( "#save").on("click",function (e) {
            e.preventDefault();
            var $flag = true;
            if ($flag == true) {
                var action = $("#form-action").attr("action");
                var request_method = $("#form-action").attr("method");
                var form_data = new FormData(document.getElementById('form-action'));
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url: action,
                    type: request_method,
                    data: form_data,
                    processData: false,
                    contentType: false,
                    cache: false,
                    error: function(xhr, ajaxOptions, thrownError) {
                        alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                    }
                }).done(function (data) {
                    if(data.success){
                        load_list_post_cat();
                        load_list_parent_cat();
                        if(data.result == 'add'){
                            iziToast.success({
                                position: 'topCenter',
                                title: '@lang('admin.info')',
                                message: data.success
                            });
                        }else{
                            $('#myModal').modal('hide');
                            iziToast.success({
                                position: 'topCenter',
                                title: '@lang('admin.info')',
                                message: data.success
                            });
                        }
                    }else{
                        jQuery.each(data.errors, function(key, value){
                            iziToast.error({
                                position: 'topRight',
                                title: '@lang('admin.info')',
                                message: value
                            });
                        });
                    }
                });
            }
        });
    });
</script>

resources/views/admin/post/post_detail.blade.php
        <div id="page-content">
            <div class="panel blog blog-details">
                <div class="panel-body">
                    <div class="blog-title media-block">
                        <div class="media-right textright">
                            <a href="#" class="btn btn-icon demo-psi-twitter icon-lg add-tooltip" data-original-title="Twitter" data-container="body"></a>
                            <a href="#" class="btn btn-icon demo-psi-instagram icon-lg add-tooltip" data-original-title="Instagram" data-container="body"></a>
                        </div>
                        <div class="media-body">
                            {{--<a href="#" class="btn-link">--}}
                                <h1>Tiêu đề: {{ $post->title }}</h1>
                            {{--</a>--}}
                            <p>@lang('admin.by')
                                <a href="#" class="btn">{{ $post->user->name }}
                                    <span class="label label-success">{{ $post->CreatedDate }}</span>
                                </a>
                            </p>
                            <p>
                                @lang('admin.number_view'): <span class="mar-rgt"> {{ $post->viewer }} @lang('admin.view')</span>
                                <br>
                            </p>
                            <p>Mô tả: {{ $post->description }}</p>
                            {{--<p>--}}
                                {{--@lang('admin.status'): <span class="mar-rgt"> {{ $page->Statu }} @lang('admin.view')</span>--}}
                            {{--</p>--}}
                        </div>
                    </div>
                    <hr>
                    <img src="{{ asset($post->image) }}" alt="" style="width: 90%; height: auto;">
                    <div class="blog-content">
                        <div class="blog-body">
                            {!! $post->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>