routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Spatie\Activitylog\Models\Activity;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('admin')->prefix('admin')->name('admin.')->group(function (){
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
//	ADMIN_PAGE
	Route::resource('/page','PageController');
	Route::post('/page/updateStatus', 'PageController@updateStatus')->name('page.updateStatus');
	Route::post('/page/deletePage', 'PageController@deletePage')->name('page.deletePage');
	Route::get('/page/getAjaxForm', 'PageController@getAjaxForm')->name('page.getAjaxForm');
	Route::post('/page/action', 'PageController@action')->name('page.action');
// ADMIN_POST CAT
	Route::resource('/post_cat','PostCatController');
	Route::get('/postCat/getListPostCat', 'PostCatController@getListPostCat')->name('postCat.getListPostCat');
	Route::get('/postCat/getListParent', 'PostCatController@getListParent')->name('postCat.getListParent');
	Route::post('/postCat/deletePostCat', 'PostCatController@deletePostCat')->name('postCat.deletePostCat');
	Route::post('/postCat/action', 'PostCatController@action')->name('postCat.action');
//	ADMIN POST
	Route::resource('/post','PostController');
	Route::post('/post/updateStatus', 'PostController@updateStatus')->name('post.updateStatus');
	Route::post('/post/deletePost', 'PostController@deletePost')->name('post.deletePost');
	Route::post('/post/action', 'PostController@action')->name('post.action');

});
Route::get('/test',function (){
//	$activity = Activity::all()->last();
//	dd($activity->changes());
//	$data = auth('admin')->user()->activity;
//	dd($data);
});
//Route::namespace('ajax')->prefix('ajax')->name('ajax.')->group(function (){
//	Route::post('/page', 'PageController@index')->name('page');
//});

resources/views/admin/layouts/footer.blade.php
<!-- FOOTER -->
<!--===================================================-->
<footer id="footer">

    <!-- Visible when footer positions are fixed -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="show-fixed pad-rgt pull-right">
        You have
        <a href="#" class="text-main">
            <span class="badge badge-danger">3</span> pending action.</a>
    </div>



    <!-- Visible when footer positions are static -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="hide-fixed pull-right pad-rgt">
        14GB of
        <strong>512GB</strong> Free.
    </div>



    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Remove the class "show-fixed" and "hide-fixed" to make the content always appears. -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

    <p class="pad-lft">&#0169; 2017 Your Company</p>



</footer>
<!--===================================================-->
<!-- END FOOTER -->

resources/views/admin/layouts/index.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ asset('admin/img/logo.png') }}" />

    <title>@yield('title','Admin CMS')</title>


    <!--STYLESHEET-->
    <!--=================================================-->

    <!--Open Sans Font [ OPTIONAL ]-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>


    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="{{ asset('admin/css/bootstrap.min.css') }}" rel="stylesheet">


    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="{{ asset('admin/css/nifty.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/css/nifty-theme.css') }}" rel="stylesheet">

    <!--Nifty Premium Icon [ DEMONSTRATION ]-->
    <link href="{{ asset('admin/css/demo/nifty-demo-icons.min.css') }}" rel="stylesheet">


    <!--=================================================-->



    <!--Pace - Page Load Progress Par [OPTIONAL]-->
    <link href="{{ asset('admin/plugins/pace/pace.min.css') }}" rel="stylesheet">
    <script src="{{ asset('admin/plugins/pace/pace.min.js')}}"></script>


    <!--Demo [ DEMONSTRATION ]-->
    <link href="{{ asset('admin/css/demo/nifty-demo.min.css')}}" rel="stylesheet">



    <!--Custom scheme [ OPTIONAL ]-->
    <link href="{{ asset('admin/css/themes/type-c/theme-navy.min.css')}}" rel="stylesheet">

    <!--Font Awesome [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <!--DataTables [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/datatables/media/css/dataTables.bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css')}}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('admin/css/jquery.dataTables.min.css')}}">
    {{--iziToast - THÔNG BÁO--}}
    <link rel="stylesheet" href="{{ asset('iziToast/dist/css/iziToast.css')}}">
    {{--LOADING MODAL--}}
    <link rel="stylesheet" href="{{ asset('admin/css/loading.css')}}">
    <!--Bootstrap Validator [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/bootstrap-validator/bootstrapValidator.min.css')}}" rel="stylesheet">
    {{--Datatables --}}
    <link rel="stylesheet" href="{{ asset('admin/css/datatable.css')}}">
    <!--Bootstrap Timepicker [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css')}}" rel="stylesheet">
    <!--Bootstrap Datepicker [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css')}}" rel="stylesheet">
    <!--Bootstrap Select [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/bootstrap-select/bootstrap-select.min.css')}}" rel="stylesheet">
    <!--Select2 [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/select2/css/select2.min.css')}}" rel="stylesheet">
    <!--Summernote [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/summernote/summernote.min.css')}}" rel="stylesheet">
    <!--Dropzone [ OPTIONAL ]-->
    <link href="{{ asset('admin/plugins/dropzone/dropzone.min.css')}}" rel="stylesheet">
</head>

<!--TIPS-->
<!--You may remove all ID or Class names which contain "demo-", they are only used for demonstration. -->

<body>
<div id="container" class="effect aside-float aside-bright mainnav-lg">
    @include('admin.layouts.header')
    @yield('content')
    @include('admin.layouts.siderbar')
    @include('admin.layouts.footer')

    <!-- SCROLL PAGE BUTTON -->
    <!--===================================================-->
    <button class="scroll-top btn">
        <i class="pci-chevron chevron-up"></i>
    </button>
    <!--===================================================-->



</div>
<!--===================================================-->
<!-- END OF CONTAINER -->





<!--JAVASCRIPT-->
<!--=================================================-->

<!--jQuery [ REQUIRED ]-->
<script src="{{ asset('admin/js/jquery.min.js')}}"></script>


<!--BootstrapJS [ RECOMMENDED ]-->
<script src="{{ asset('admin/js/bootstrap.min.js')}}"></script>


<!--NiftyJS [ RECOMMENDED ]-->
<script src="{{ asset('admin/js/nifty.min.js')}}"></script>




<!--=================================================-->

<!--Demo script [ DEMONSTRATION ]-->
<script src="{{ asset('admin/js/demo/nifty-demo.min.js')}}"></script>


<!--Flot Chart [ OPTIONAL ]-->
<script src="{{ asset('admin/plugins/flot-charts/jquery.flot.min.js')}}"></script>
<script src="{{ asset('admin/plugins/flot-charts/jquery.flot.categories.min.js')}}"></script>
<script src="{{ asset('admin/plugins/flot-charts/jquery.flot.orderBars.min.js')}}"></script>
<script src="{{ asset('admin/plugins/flot-charts/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{ asset('admin/plugins/flot-charts/jquery.flot.resize.min.js')}}"></script>


<!--Specify page [ SAMPLE ]-->
{{--<script src="{{ asset('admin/js/demo/dashboard-2.js')}}"></script>--}}
<!--DataTables [ OPTIONAL ]-->
<script src="{{ asset('admin/plugins/select2/js/select2.min.js')}}"></script>
<!--Bootstrap Timepicker [ OPTIONAL ]-->
<script src="{{ asset('admin/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js')}}"></script>
<!--Bootstrap Datepicker [ OPTIONAL ]-->
<script src="{{ asset('admin/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js')}}"></script>
<script src="{{ asset('admin/plugins/datatables/media/js/jquery.dataTables.js')}}"></script>
<script src="{{ asset('admin/plugins/datatables/media/js/dataTables.bootstrap.js')}}"></script>
<script src="{{ asset('admin/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset('admin/js/demo/tables-datatables.js')}}"></script>
<script src="{{ asset('admin/js/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('admin/plugins/bootstrap-select/bootstrap-select.min.js')}}"></script>
<!--Form File Upload [ SAMPLE ]-->
<!--Summernote [ OPTIONAL ]-->
<script src="{{ asset('admin/plugins/summernote/summernote.min.js') }}"></script>
<script src="{{ asset('admin/js/demo/form-text-editor.js')}}"></script>
{{--iziToast--}}
<script src="{{ asset('iziToast/dist/js/iziToast.js')}}"></script>
<script>
    // Loading in AJAX
    var $loading = $('.loader').hide();
    var $modal_header = $('.modal-header').hide();
    $(document)
        .ajaxStart(function () {
            $loading.show();
            $modal_header.hide();
            $('.modal-body').css('display', 'none');
            $('.modal-content').css('width', '200px');
            $('.modal-content').css('left', 'calc(50% - 100px)');
            $('.modal-footer').css('display', 'none');
        })
        .ajaxStop(function () {
            $loading.hide();
            $modal_header.show();
            $('.modal-body').css('display', 'block');
            $('.modal-content').css('width', 'auto');
            $('.modal-content').css('left', '0px');
            $('.modal-footer').css('display', 'block');
        });
</script>
@yield('js')
</body>

</html>

resources/views/admin/layouts/siderbar.blade.php
<!--MAIN NAVIGATION-->
<!--===================================================-->
<nav id="mainnav-container">
    <div id="mainnav">


        <!--OPTIONAL : ADD YOUR LOGO TO THE NAVIGATION-->
        <!--It will only appear on small screen devices.-->
        <!--================================
        <div class="mainnav-brand">
            <a href="index.html" class="brand">
                <img src="img/logo.png" alt="Nifty Logo" class="brand-icon">
                <span class="brand-text">Nifty</span>
            </a>
            <a href="#" class="mainnav-toggle"><i class="pci-cross pci-circle icon-lg"></i></a>
        </div>
        -->



        <!--Menu-->
        <!--================================-->
        <div id="mainnav-menu-wrap">
            <div class="nano">
                <div class="nano-content">

                    <!--Shortcut buttons-->
                    <!--================================-->
                    {{--<div id="mainnav-shortcut" class="hidden">--}}
                        {{--<ul class="list-unstyled shortcut-wrap">--}}
                            {{--<li class="col-xs-3" data-content="My Profile">--}}
                                {{--<a class="shortcut-grid" href="#">--}}
                                    {{--<div class="icon-wrap icon-wrap-sm icon-circle bg-mint">--}}
                                        {{--<i class="demo-pli-male"></i>--}}
                                    {{--</div>--}}
                                {{--</a>--}}
                            {{--</li>--}}
                            {{--<li class="col-xs-3" data-content="Messages">--}}
                                {{--<a class="shortcut-grid" href="#">--}}
                                    {{--<div class="icon-wrap icon-wrap-sm icon-circle bg-warning">--}}
                                        {{--<i class="demo-pli-speech-bubble-3"></i>--}}
                                    {{--</div>--}}
                                {{--</a>--}}
                            {{--</li>--}}
                            {{--<li class="col-xs-3" data-content="Activity">--}}
                                {{--<a class="shortcut-grid" href="#">--}}
                                    {{--<div class="icon-wrap icon-wrap-sm icon-circle bg-success">--}}
                                        {{--<i class="demo-pli-thunder"></i>--}}
                                    {{--</div>--}}
                                {{--</a>--}}
                            {{--</li>--}}
                            {{--<li class="col-xs-3" data-content="Lock Screen">--}}
                                {{--<a class="shortcut-grid" href="#">--}}
                                    {{--<div class="icon-wrap icon-wrap-sm icon-circle bg-purple">--}}
                                        {{--<i class="demo-pli-lock-2"></i>--}}
                                    {{--</div>--}}
                                {{--</a>--}}
                            {{--</li>--}}
                        {{--</ul>--}}
                    {{--</div>--}}
                    <!--================================-->
                    <!--End shortcut buttons-->


                    <ul id="mainnav-menu" class="list-group">

                        <!--Category name-->
                        <li class="list-header"></li>

                        <!--Menu list item-->
                        <li class="active-sub">
                            <a href="{{ route('admin.home') }}">
                                <i class="demo-pli-home"></i>
                                <span class="menu-title">Trang chủ</span>
                            </a>
                        </li>
                        <!--Page list item-->
                        <li>
                            <a href="{{ route('admin.page.index') }}">
                                <i class="demo-pli-split-vertical-2"></i>
                                <span class="menu-title">Trang</span>
                            </a>
                        </li>
                        <!--Page list item-->
                        <li>
                            <a href="#">
                                <i class="demo-pli-receipt-4"></i>
                                <span class="menu-title">Quản Lý Bài Viết</span>
                                <i class="arrow"></i>
                            </a>
                            <!--Submenu-->
                            <ul class="collapse">
                                <li>
                                    <a href="{{ route('admin.post.index') }}">Bài viết</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.post_cat.index') }}">Danh mục bài viết</a>
                                </li>
                            </ul>
                        </li>
                        <!--Product list item-->
                        <li>
                            <a href="#">
                                <i class="fa fa-ambulance"></i>
                                <span class="menu-title">Quản lý sản phẩm</span>
                                <i class="arrow"></i>
                            </a>
                            <!--Submenu-->
                            <ul class="collapse">
                                <li>
                                    <a href="layouts-offcanvas-navigation.html">Sản phẩm</a>
                                </li>
                                <li>
                                    <a href="layouts-collapsed-navigation.html">Danh mục Sản phẩm</a>
                                </li>

                            </ul>
                        </li>
                        <li class="list-divider"></li>
                    </ul>

                </div>
            </div>
        </div>
        <!--================================-->
        <!--End menu-->

    </div>
</nav>
<!--===================================================-->
<!--END MAIN NAVIGATION-->